{% set name = "fsl-pyfeeds" %}
{% set version = "0.9.4" %}
{% set sha256 = "dfbbefc28018c86d09196ad217a1b7818b3bdf20761682f48535688b7374ce16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyfeeds = pyfeeds.main:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.11
    - nibabel >=2.1

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - pytest -v --cov=pyfeeds --pyargs pyfeeds.tests

about:
  home: https://git.fmrib.ox.ac.uk/fsl/pyfeeds
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'FSL testing framework'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/pyfeeds

extra:
  recipe-maintainers:
    - pauldmccarthy
