{% set name = "fsl-pyfeeds" %}
{% set version = "0.9.1" %}
{% set sha256 = "89e214bc7f2c717922183f03d3d87a2eebf1d4016748330615a5975c834b81b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyfeeds = pyfeeds.main:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.11
    - nibabel >=2.1

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - pytest -v --cov=pyfeeds --pyargs pyfeeds.tests

about:
  home: https://git.fmrib.ox.ac.uk/fsl/pyfeeds
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'FSL testing framework'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/pyfeeds

extra:
  recipe-maintainers:
    - pauldmccarthy
