travis:
  secure:
    BINSTAR_TOKEN: DOJNlTaV6ieEwLNKEs+wbfWoi4ftPwVFR36jKSRV0Jll7Sz5pULqzl+LLMEmeP8RBiFbvrNXYQh7jNUPuHO8JsaOgBX/I0obg8Y76VY5tDOBRd8ZqprFTeh7Q/kqQDUhdzqVlxIc4MjFCnyxBImQVww1n+ryhIhTQPQpfmNxAHW8fiTRaDH6dX7To/VIfCVc6zJEJbDXnAOzRc7wLXNeKE10zgqyTYo8TRr7MKzJeqF9eGbmpc1EoZegmR0buC+FVLvBvOblTzE3pdBrvo8UIlsZJz65+swzCpGkQ5sDyeXU0StPVFwRnLAarP60FM04SgFwN3N4pU8Sv0iRkHKZCpiwzAaC7lOPI+DkDyoGQ4VmfGO6PZTtvE5dK1amXtvBePilgZrhonzwUT82sJF0O2VnplBQVXsh1BdRsbY6/4M9kTl3c4lz1UPKN8JyNjPzJkpdftzcJVk1LapuvvBvi6ICCs6yRPUcfx9eDDTJLF3ADDLzokdPUhguJmmBgfGb1gJSQDzI7Q2O8cfWvybNeO8KqYS5Qvvwxex65LFtZjXrzFEPuGSruutiFaNgVVPLrCLBcyIDC9QTKzCQ/9MSGpqNvJT1R/dpZSC4VzxtMyv12zyCp2RtYAYYsUdPA15P4ancbFsewuBCqAOHeJgfEFPwx++DjRKMYxdaSUcrs1M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
